# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 09:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0005_auto_20161229_0850'),
    ]

    operations = [
        migrations.CreateModel(
            name='Showtime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cinema', models.CharField(choices=[('CIVIL', 'QFX Civil Mall'), ('LABIM', 'QFX Labim Mall'), ('KUMARI', 'QFX Kumari'), ('JAINEPAL', 'QFX Jai Nepal')], max_length=10)),
                ('time', models.CharField(max_length=10)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='movies.Movie')),
            ],
        ),
    ]
