# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showtimes', '0002_showtime_booking_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='showtime',
            name='last_updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
