# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='runtime',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
