# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20161229_0704'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='last_updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
