# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 10:48
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_movie_last_updated_date'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='movie',
            managers=[
                ('recent', django.db.models.manager.Manager()),
            ],
        ),
    ]
